// <auto-generated />
namespace API.Core.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class WidgetFeature : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WidgetFeature));
        
        string IMigrationMetadata.Id
        {
            get { return "201512261635268_WidgetFeature"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
