// <auto-generated />
namespace API.Core.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class widgetPropertyAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(widgetPropertyAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201512281748366_widgetPropertyAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
